version: '3'
services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ..:/workspace/discord-bot:cached
        # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
